target:
  # url: "https://www.mizuhobank.co.jp/rate_fee/market/quote/data/quote_yyyyMMdd.txt"
  url: "https://www.mizuhobank.co.jp/market/quote/data/quote_yyyyMMdd.txt"
  savedirectory: '/opt/tools/cod/json/'